### ISSUE TITLE
Loading k2 before torch

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#473] opened 2020-12-08 12:23 UTC
Is it necessary that we get an error with loading libc10.so and so on if we load k2 before torch?  why can't we load torch from k2?  I'm sure there is a reason- just want to know what it is.

**Comment by csukuangfj** [comment] 2020-12-08 13:05
Can the import error be reproduced from the latest master?
I just tried to import `k2` without importing `torch` and there was no error.

**Comment by danpovey** [comment] 2020-12-08 13:14
Mm.  I just tried it and it worked. OK.  Not sure what happened there, but
there weren't code changes that should have affected this.
I think that was the debug build I was having problems with; right now I
have the release one built.

**Comment by qindazhu** [comment] 2020-12-09 09:19
I have the same issue with debug (I have no the issue before, even for debug)

```
>>> import k2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ceph-hw/.local/lib/python3.8/site-packages/k2/__init__.py", line 1, in <module>
    from _k2 import RaggedInt
ImportError: libc10.so: cannot open shared object file: No such file or directory

```

**Comment by qindazhu** [comment] 2020-12-09 09:23
Oops, I have the same issue even for release...

**Comment by csukuangfj** [comment] 2020-12-09 09:25
Looks like the issue is introduced by #410 
https://github.com/k2-fsa/k2/blob/10936c196fb48d6ec14dc2d6189826297bf1428f/k2/python/k2/__init__.py#L1-L2

It `import _k2` without `import torch` first.

**Comment by danpovey** [comment] 2020-12-09 09:26
Would just having __init__.py import torch resolve it, perhaps?
I don't know much about the subtleties of module load order in python.

**Comment by csukuangfj** [comment] 2020-12-09 09:28
> Would just having `__init__.py` import torch resolve it, perhaps?

I guess so.

From https://pytorch.org/cppdocs/notes/faq.html#undefined-symbol-errors-from-pytorch-aten

> Problem: You import your extension and get an ImportError stating that some C++ symbol from PyTorch or ATen is undefined. For example:

> Fix: The fix is to import torch before you import your extension. This will make the symbols from the PyTorch dynamic (shared) library that your extension depends on available, allowing them to be resolved once you import your extension.

**Comment by qindazhu** [comment] 2020-12-09 09:37
Yeah, it works.

**Comment by qindazhu** [comment] 2020-12-09 10:31
Fixed with https://github.com/k2-fsa/k2/pull/483, closed.

**Closed by qindazhu** 2020-12-09 10:31 UTC
