### ISSUE TITLE
Nbest online decoding bug

### ISSUE THREAD

**Issue by binhtranmcs** [k2-fsa/k2#1276] opened 2024-04-10 08:37 UTC
I tried online decoding using the file `online_decode.cu` and modified a bit to get nbest from the lattice. But I get errors. The assertion is in `fsa_utils.cu` line [2754](https://github.com/k2-fsa/k2/blob/master/k2/csrc/fsa_utils.cu#L2754).

The offline decoding seems fine. So I suspect there is something wrong with the online implementation. Also, it does not happen to all audios tested. Please help me with this.

Model: [librispeech conformer ctc](https://huggingface.co/csukuangfj/icefall-asr-librispeech-conformer-ctc-jit-bpe-500-2021-11-09/tree/main)
Code: [online_decode.txt](https://github.com/k2-fsa/k2/files/14929700/online_decode.txt)
Log debug: [error.log](https://github.com/k2-fsa/k2/files/14929683/error.log)

Thanks!

**Comment by csukuangfj** [comment] 2024-04-10 09:57
@pkufool Could you have a look?

**Comment by trangtv57** [comment] 2024-04-10 10:19
i have same issuse, pls, fast check this error :(

**Comment by cudothanh-Nhan** [comment] 2024-04-11 04:31
Same with me :(

**Comment by pkufool** [comment] 2024-04-11 04:40
OK, I will have a look soon.

**Comment by trangtv57** [comment] 2024-04-17 09:06
sorry but any update @pkufool pk?

**Comment by pkufool** [comment] 2024-04-22 03:13
@trangtv57  Sorry for the late responds.  I reproduced your issue, the error seems happen on the invert of the generated lattice.  There is a quick fix at https://github.com/k2-fsa/k2/pull/1280 , it works fine on the given conformer-ctc model above. Pls help to do more tests, thanks!

**Comment by trangtv57** [comment] 2024-04-22 03:27
tks @pkufool, i will check it then feedback you soon.

**Comment by binhtranmcs** [comment] 2024-04-22 05:07
tks @pkufool, I just tested again with the model above and it seems fine. But when decoding with my own model, there is still error, the assertion in `fsa_utils.cu` line [2756](https://github.com/k2-fsa/k2/blob/master/k2/csrc/fsa_utils.cu#L2756). Please have a further look.

**Comment by pkufool** [comment] 2024-04-22 06:39
> tks @pkufool, I just tested again with the model above and it seems fine. But when decoding with my own model, there is still error, the assertion in `fsa_utils.cu` line [2756](https://github.com/k2-fsa/k2/blob/master/k2/csrc/fsa_utils.cu#L2756). Please have a further look.

If it is line 2756 in `fsa_utils.cu` , I think it is the same issue. Could you make sure that (for example, testing with more cases) it works fine with our model?    It will be easier for me to debug if I have the model that can reproduce it. Thank you!

**Comment by binhtranmcs** [comment] 2024-04-22 07:53
@pkufool, I tested again with the audio below (change extension to .wav), and got a different the error:
```
[F] /home/cpu13266/binhtt4/clone/k2/k2/csrc/array.h:385:T k2::Array1<T>::operator[](int32_t) const [with T = int; int32_t = int] Check failed: ret == cudaSuccess (700 vs. 0)  Error: an illegal memory access was encountered. 
```
You can try to debug with it, same model as above.

[61-70970-0031.txt](https://github.com/k2-fsa/k2/files/15059390/61-70970-0031.txt)

**Comment by danpovey** [comment] 2024-04-23 05:28
I merged Kangwei's fix as it seems to be a straightforward fix of an undefined value, if there are further bugs we can fix separately.

**Closed** 2024-04-23 05:27 UTC

**Comment by pkufool** [comment] 2024-04-24 12:18
@binhtranmcs  Here is anther fix https://github.com/k2-fsa/k2/pull/1282 , I think previous fix  #1280 introduced the bug.

**Comment by binhtranmcs** [comment] 2024-04-25 12:56
@pkufool, I tested with the librispeech dataset and it ran smoothly. But there is still error when tested with the audio below (change ext to .wav):
```
[F] /home/cpu13266/binhtt4/clone/k2/k2/csrc/top_sort.cu:324:k2::FsaVec k2::TopSorter::TopSort(k2::Array1<int>*) Check failed: start_state_present[0] == 1 (0 vs. 1) Our current implementation requires that the start state in each Fsa must be present in the first batch
```
[nbest-err.txt](https://github.com/k2-fsa/k2/files/15110106/nbest-err.txt)

**Comment by binhtranmcs** [comment] 2024-04-26 10:15
@pkufool fyi
```
__GI_raise 0x00007fff9700400b
k2::internal::Logger::~Logger log.h:203
k2::TopSorter::TopSort top_sort.cu:324
k2::TopSort top_sort.cu:371
k2::TopSort fsa_algo.cu:141
k2::Nbest::Intersect nbest.cu:77
main online_decode.cu:336
```
The log:
```
[F] /home/cpu13266/binhtt4/clone/k2/k2/csrc/top_sort.cu:324:k2::FsaVec k2::TopSorter::TopSort(k2::Array1<int>*) Check failed: start_state_present[0] == 1 (0 vs. 1) Our current implementation requires that the start state in each Fsa must be present in the first batch


[ Stack-Trace: ]
/home/cpu13266/binhtt4/clone/k2/cmake-build-debug/lib/libk2_log.so(k2::internal::GetStackTrace()+0x5f) [0x7ffff641f34a]
/home/cpu13266/binhtt4/clone/k2/cmake-build-debug/bin/online_decode(k2::internal::Logger::~Logger()+0x48) [0x5555555a829e]
/home/cpu13266/binhtt4/clone/k2/cmake-build-debug/lib/libk2context.so(k2::TopSorter::TopSort(k2::Array1<int>*)+0x3cc) [0x7ffff6a3fad4]
/home/cpu13266/binhtt4/clone/k2/cmake-build-debug/lib/libk2context.so(k2::TopSort(k2::Ragged<k2::Arc>&, k2::Ragged<k2::Arc>*, k2::Array1<int>*)+0x3a7) [0x7ffff6a3778a]
/home/cpu13266/binhtt4/clone/k2/cmake-build-debug/lib/libk2_torch.so(k2::TopSort(k2::FsaClass*)+0x58) [0x7ffff7896a62]
/home/cpu13266/binhtt4/clone/k2/cmake-build-debug/lib/libk2_torch.so(k2::Nbest::Intersect(k2::FsaClass*)+0x41d) [0x7ffff78b6cef]
/home/cpu13266/binhtt4/clone/k2/cmake-build-debug/bin/online_decode(+0x4fba2) [0x5555555a3ba2]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fff96fe5083]
/home/cpu13266/binhtt4/clone/k2/cmake-build-debug/bin/online_decode(+0x4d79e) [0x5555555a179e]

terminate called after throwing an instance of 'std::runtime_error'
  what():  
    Some bad things happened. Please read the above error messages and stack
    trace. If you are using Python, the following command may be helpful:

      gdb --args python /path/to/your/code.py

    (You can use `gdb` to debug the code. Please consider compiling
    a debug version of k2.).

    If you are unable to fix it, please open an issue at:

      https://github.com/k2-fsa/k2/issues/new
    
Signal: SIGABRT (Aborted)

```
Also the code I use: [online_decode.cu.txt](https://github.com/k2-fsa/k2/files/15129217/online_decode.cu.txt)
